# Generated by Django 2.1 on 2018-08-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='action_time',
            new_name='action_start',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='habit_action',
            new_name='habit',
        ),
        migrations.AddField(
            model_name='action',
            name='action_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
