# Generated by Django 2.1 on 2018-09-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_auto_20180824_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
