# Generated by Django 2.1 on 2018-09-09 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0004_auto_20180909_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_start', models.DateTimeField(blank=True, null=True)),
                ('mood_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mood',
            name='mood_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mood',
            name='mood_weight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moodtracking',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.Mood'),
        ),
        migrations.AddField(
            model_name='moodtracking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
