# Generated by Django 2.1 on 2018-08-22 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_auto_20180821_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='original',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='thread_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forums.Thread'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forums.Subject'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='subject_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='forums.Subject'),
        ),
    ]
